fix: Wrong link to documentation in readme
invertase/flutterfire_cli pull request #113
Opened 2022-10-08 13:49 UTC by bhattabhi013

## Description

Fix issue#106: Wrong link to documentation in the readme.
Changed the link from `https://firebase.flutter.dev/docs/cli/` to `https://firebase.google.com/docs/flutter/setup`.

## Type of Change

- [ ] ✨ `feat` -- New feature (non-breaking change which adds functionality)
- [x] 🛠️ `fix` -- Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ `!` -- Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 `refactor` -- Code refactor
- [ ] ✅ `ci` -- Build configuration change
- [ ] 📝 `docs` -- Documentation
- [ ] 🗑️ `chore` -- Chore

2022-10-09 13:58 UTC, bhattabhi013 commented
@Lyokone , Can you please review this one?

2022-10-10 07:53 UTC, Lyokone requested changes

2022-10-10 14:50 UTC, bhattabhi013 commented on README.md
> +  <a href="https://firebase.google.com/docs/flutter/setup?platform=ios">Documentation</a> &bull;
Thanks for reviewing and suggestions.
I've done the needful.

2022-10-11 07:10 UTC, Lyokone approved these changes

2022-10-11 07:49 UTC, Ehesp approved these changes

2022-10-11 12:31 UTC, bhattabhi013 commented
Hy maintainers,
Does it come under hacktoberfest?

2022-10-13 06:37 UTC, merged

2022-10-13 06:42 UTC, Lyokone commented
Hello @bhattabhi013,
This PR does not qualify for hacktoberfest, see here for more information: https://invertase.io/community/hacktoberfest
Thanks for your contribution :)